ALTER TABLE notifications
    MODIFY COLUMN type ENUM(
        'MAINTENANCE_REMINDER',
        'MAINTENANCE_OVERDUE',
        'TASK_ASSIGNED',
        'TASK_COMPLETED',
        'TASK_REJECTED',
        'CONSULTATION_ASSIGNED',
        'MAINTENANCE_REMINDER_7',
        'MAINTENANCE_REMINDER_3',
        'MAINTENANCE_REMINDER_1',
        'MAINTENANCE_OVERDUE_ALERT',
        'MAINTENANCE_SUBMITTED',
        'MAINTENANCE_APPROVED',
        'MAINTENANCE_REJECTED',
        'MAINTENANCE_MORE_EVIDENCE'
    ) NOT NULL;